#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import { basename } from "node:path";

const [, , sourcePath, outputPath, heightText = "46"] = process.argv;
if (!sourcePath || !outputPath) {
  throw new Error("Usage: node scripts/voxelize-obj.mjs <source.obj> <output.ts> [target-height]");
}

const targetHeight = Number(heightText);
if (!Number.isFinite(targetHeight) || targetHeight < 8) throw new Error("Target height must be at least 8 voxels");

const source = await readFile(sourcePath, "utf8");
const vertices = [];
const sourceTriangles = [];

for (const line of source.split(/\r?\n/)) {
  const parts = line.trim().split(/\s+/);
  if (parts[0] === "v" && parts.length >= 4) {
    vertices.push(parts.slice(1, 4).map(Number));
  } else if (parts[0] === "f" && parts.length >= 4) {
    const indices = parts.slice(1).map((part) => {
      const raw = Number(part.split("/")[0]);
      return raw < 0 ? vertices.length + raw : raw - 1;
    });
    for (let index = 1; index < indices.length - 1; index += 1) {
      sourceTriangles.push([indices[0], indices[index], indices[index + 1]]);
    }
  }
}

if (!vertices.length || !sourceTriangles.length) throw new Error("OBJ has no usable geometry");

const bounds = vertices.reduce((result, [x, y, z]) => ({
  minX: Math.min(result.minX, x), maxX: Math.max(result.maxX, x),
  minY: Math.min(result.minY, y), maxY: Math.max(result.maxY, y),
  minZ: Math.min(result.minZ, z), maxZ: Math.max(result.maxZ, z),
}), { minX: Infinity, maxX: -Infinity, minY: Infinity, maxY: -Infinity, minZ: Infinity, maxZ: -Infinity });

// This source uses OBJ Z as height. Convert to game X/Y/Z and centre the footprint.
const scale = targetHeight / (bounds.maxZ - bounds.minZ);
const centreX = (bounds.minX + bounds.maxX) / 2;
const centreDepth = (bounds.minY + bounds.maxY) / 2;
const transformed = vertices.map(([x, y, z]) => [
  (x - centreX) * scale,
  (z - bounds.minZ) * scale,
  (y - centreDepth) * scale,
]);

const triangles = sourceTriangles.map((indices) => indices.map((index) => transformed[index]));
const voxels = new Set();
const add = (x, y, z) => voxels.add(`${Math.round(y)},${Math.round(z)},${Math.round(x)}`);
const distance = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);

// Sample every face densely so thin mouldings survive the conversion.
for (const [a, b, c] of triangles) {
  const steps = Math.max(1, Math.ceil(Math.max(distance(a, b), distance(b, c), distance(c, a)) * 1.8));
  for (let row = 0; row <= steps; row += 1) {
    for (let column = 0; column <= steps - row; column += 1) {
      const u = row / steps;
      const v = column / steps;
      const w = 1 - u - v;
      add(
        a[0] * w + b[0] * u + c[0] * v,
        a[1] * w + b[1] * u + c[1] * v,
        a[2] * w + b[2] * u + c[2] * v,
      );
    }
  }
}

const meshBounds = transformed.reduce((result, [x, y, z]) => ({
  minX: Math.min(result.minX, x), maxX: Math.max(result.maxX, x),
  minY: Math.min(result.minY, y), maxY: Math.max(result.maxY, y),
  minZ: Math.min(result.minZ, z), maxZ: Math.max(result.maxZ, z),
}), { minX: Infinity, maxX: -Infinity, minY: Infinity, maxY: -Infinity, minZ: Infinity, maxZ: -Infinity });

// Fill closed parts with scanlines through the model depth while keeping arches hollow.
for (let x = Math.floor(meshBounds.minX); x <= Math.ceil(meshBounds.maxX); x += 1) {
  for (let y = Math.floor(meshBounds.minY); y <= Math.ceil(meshBounds.maxY); y += 1) {
    const intersections = [];
    for (const [a, b, c] of triangles) {
      const denominator = (b[1] - c[1]) * (a[0] - c[0]) + (c[0] - b[0]) * (a[1] - c[1]);
      if (Math.abs(denominator) < 1e-8) continue;
      const u = ((b[1] - c[1]) * (x - c[0]) + (c[0] - b[0]) * (y - c[1])) / denominator;
      const v = ((c[1] - a[1]) * (x - c[0]) + (a[0] - c[0]) * (y - c[1])) / denominator;
      const w = 1 - u - v;
      if (u < -1e-6 || v < -1e-6 || w < -1e-6) continue;
      intersections.push(u * a[2] + v * b[2] + w * c[2]);
    }
    intersections.sort((left, right) => left - right);
    const unique = intersections.filter((value, index) => index === 0 || Math.abs(value - intersections[index - 1]) > 0.08);
    for (let index = 0; index + 1 < unique.length; index += 2) {
      for (let z = Math.ceil(unique[index]); z <= Math.floor(unique[index + 1]); z += 1) add(x, y, z);
    }
  }
}

const coordinates = [...voxels].map((key) => key.split(",").map(Number));
coordinates.sort((left, right) => left[0] - right[0] || left[1] - right[1] || left[2] - right[2]);
const spans = [];
for (const [y, z, x] of coordinates) {
  const last = spans.at(-1);
  if (last && last[0] === y && last[1] === z && last[3] + 1 === x) last[3] = x;
  else spans.push([y, z, x, x]);
}

const generated = `// Generated by scripts/voxelize-obj.mjs from ${basename(sourcePath)}.\n` +
  `// Derived from "India Gate" by sujankdh: https://www.thingiverse.com/thing:7027090\n` +
  `// Source and voxel data are licensed CC BY-SA; see assets/source/india-gate/README.md.\n\n` +
  `export type VoxelSpan = readonly [y: number, z: number, minX: number, maxX: number];\n\n` +
  `export const INDIA_GATE_VOXEL_COUNT = ${coordinates.length};\n` +
  `export const INDIA_GATE_BOUNDS = ${JSON.stringify({
    minX: Math.floor(meshBounds.minX), maxX: Math.ceil(meshBounds.maxX),
    minY: Math.floor(meshBounds.minY), maxY: Math.ceil(meshBounds.maxY),
    minZ: Math.floor(meshBounds.minZ), maxZ: Math.ceil(meshBounds.maxZ),
  })} as const;\n\n` +
  `export const INDIA_GATE_VOXELS: readonly VoxelSpan[] = [\n${spans.map((span) => `  [${span.join(", ")}],`).join("\n")}\n] as const;\n`;

await writeFile(outputPath, generated);
console.log(`Voxelized ${vertices.length} vertices / ${sourceTriangles.length} triangles into ${coordinates.length} blocks and ${spans.length} spans.`);
